blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/and3rn3t/homehub/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/and3rn3t/homehub/security/advisories/new
    about: Report security vulnerabilities privately
