name = "homehub-kv-worker"
main = "src/index.ts"
compatibility_date = "2024-10-09"

# KV Namespace Bindings
[[kv_namespaces]]
binding = "HOMEHUB_KV"
id = "13b0979fda8e4bd0a581f4b4ddd9b92f"
preview_id = "9316570aa53747fcbae0f8f90d126408"

[[kv_namespaces]]
binding = "LOGS_KV"
id = "a4a51b7c589046ea8c42f23711ab1582"
preview_id = "6f723c57974d49fb980b1f57563e56a0"

# Worker settings
[build]
command = "npm run build"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
