name: Dependency Review

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail the build on critical vulnerabilities
          fail-on-severity: critical
          # Allow moderate and low vulnerabilities
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
          # Comment on PR with summary
          comment-summary-in-pr: always
          # Deny packages from these registries (if needed)
          # deny-packages: malicious-package
