name: Lighthouse Performance Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every Monday at 3am
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run Lighthouse CI
        run: npm run lighthouse:ci
        continue-on-error: true

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: lighthouse/reports/
          retention-days: 30

      - name: Comment PR with Lighthouse results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        continue-on-error: true
        with:
          script: |
            const fs = require('fs');

            // Check if comparison file exists
            const comparisonPath = 'lighthouse/reports/comparison.json';
            if (!fs.existsSync(comparisonPath)) {
              console.log('No comparison file found, skipping PR comment');
              return;
            }

            const comparison = JSON.parse(fs.readFileSync(comparisonPath, 'utf8'));

            const comment = `## 🏎️ Lighthouse Performance Report

            | Metric | Score | Change |
            |--------|-------|--------|
            | Performance | ${comparison.current.performance || 'N/A'} | ${comparison.diff?.performance || 'N/A'} |
            | Accessibility | ${comparison.current.accessibility || 'N/A'} | ${comparison.diff?.accessibility || 'N/A'} |
            | Best Practices | ${comparison.current['best-practices'] || 'N/A'} | ${comparison.diff?.['best-practices'] || 'N/A'} |
            | SEO | ${comparison.current.seo || 'N/A'} | ${comparison.diff?.seo || 'N/A'} |

            [View detailed report](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
